#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Tue Nov 02 22:17:07 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class CustomFilterPanel(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: CustomFilterPanel.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.searchSizer_staticbox = wx.StaticBox(self, -1, "search")
        self.reservedSizer_staticbox = wx.StaticBox(self, -1, " reserved")
        self.filterSizer_staticbox = wx.StaticBox(self, -1, "date filter")
        self.startMonthText = wx.StaticText(self, -1, "start month")
        self.startDateCombo = wx.ComboBox(self, -1, choices=[], style=wx.CB_DROPDOWN|wx.CB_DROPDOWN)
        self.startYearText = wx.StaticText(self, -1, "start year")
        self.startYearCombo = wx.ComboBox(self, -1, choices=[], style=wx.CB_DROPDOWN|wx.CB_DROPDOWN)
        self.dateRangeText = wx.StaticText(self, -1, "month range", style=wx.ALIGN_CENTRE)
        self.searchText = wx.StaticText(self, -1, "search expenses", style=wx.ALIGN_CENTRE)
        self.searchTypeText = wx.StaticText(self, -1, "search type", style=wx.ALIGN_CENTRE)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: CustomFilterPanel.__set_properties
        self.SetTitle("frame_1")
        self.SetBackgroundColour(wx.Colour(255, 255, 255))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: CustomFilterPanel.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        filterPanelSizer = wx.BoxSizer(wx.HORIZONTAL)
        reservedSizer = wx.StaticBoxSizer(self.reservedSizer_staticbox, wx.HORIZONTAL)
        searchSizer = wx.StaticBoxSizer(self.searchSizer_staticbox, wx.HORIZONTAL)
        searchSizerRight = wx.BoxSizer(wx.VERTICAL)
        searchSizerLeft = wx.BoxSizer(wx.VERTICAL)
        filterSizer = wx.StaticBoxSizer(self.filterSizer_staticbox, wx.HORIZONTAL)
        filterSizerRight = wx.BoxSizer(wx.VERTICAL)
        filterSizerMid = wx.BoxSizer(wx.VERTICAL)
        filterSizerLeft = wx.BoxSizer(wx.VERTICAL)
        filterSizerLeft.Add(self.startMonthText, 0, wx.ALIGN_CENTER_HORIZONTAL, 5)
        filterSizerLeft.Add(self.startDateCombo, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 5)
        filterSizer.Add(filterSizerLeft, 1, wx.EXPAND, 0)
        filterSizerMid.Add(self.startYearText, 0, wx.ALIGN_CENTER_HORIZONTAL, 5)
        filterSizerMid.Add(self.startYearCombo, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 5)
        filterSizer.Add(filterSizerMid, 1, wx.EXPAND, 0)
        filterSizerRight.Add(self.dateRangeText, 0, wx.ALIGN_CENTER_HORIZONTAL, 5)
        filterSizer.Add(filterSizerRight, 1, wx.EXPAND, 0)
        filterPanelSizer.Add(filterSizer, 1, wx.RIGHT|wx.EXPAND, 5)
        searchSizerLeft.Add(self.searchText, 0, wx.ALIGN_CENTER_HORIZONTAL, 5)
        searchSizer.Add(searchSizerLeft, 1, wx.EXPAND, 0)
        searchSizerRight.Add(self.searchTypeText, 0, wx.ALIGN_CENTER_HORIZONTAL, 5)
        searchSizer.Add(searchSizerRight, 1, wx.EXPAND, 0)
        filterPanelSizer.Add(searchSizer, 1, wx.EXPAND, 0)
        filterPanelSizer.Add(reservedSizer, 1, wx.LEFT|wx.EXPAND, 5)
        sizer_1.Add(filterPanelSizer, 1, wx.ALL|wx.EXPAND, 5)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class CustomFilterPanel


class FilterFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # content of this block not found: did you rename this class?
        pass

    def __set_properties(self):
        # content of this block not found: did you rename this class?
        pass

    def __do_layout(self):
        # content of this block not found: did you rename this class?
        pass

# end of class FilterFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = FilterFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
