#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Fri Nov 05 18:38:55 2010

import wx
import wx.grid

# begin wxGlade: extracode
# end wxGlade



class expenseTypeDialog(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: expenseTypeDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.deleteSizer_staticbox = wx.StaticBox(self, -1, "Delete Existing Types")
        self.newTypeSizer_staticbox = wx.StaticBox(self, -1, "Add New Types")
        self.editSizer_staticbox = wx.StaticBox(self, -1, "Edit Existing Types")
        self.expenseTypeGrid = wx.grid.Grid(self, -1, size=(1, 1))
        self.expenseTypeEditToggle = wx.ToggleButton(self, -1, "edit expense types...")
        self.deleteComboBox = wx.ComboBox(self, -1, choices=[], style=wx.CB_DROPDOWN)
        self.deleteButton = wx.Button(self, -1, "delete")
        self.newExpenseTypeEntry = wx.TextCtrl(self, -1, "new type description...")
        self.addButton = wx.Button(self, -1, "add")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: expenseTypeDialog.__set_properties
        self.SetTitle("dialog_1")
        self.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.expenseTypeGrid.CreateGrid(50, 1)
        self.expenseTypeGrid.SetRowLabelSize(30)
        self.expenseTypeGrid.SetColLabelSize(30)
        self.expenseTypeGrid.EnableDragColSize(0)
        self.expenseTypeGrid.EnableDragRowSize(0)
        self.expenseTypeGrid.EnableDragGridSize(0)
        self.expenseTypeGrid.SetColLabelValue(0, "expenseType")
        self.expenseTypeGrid.SetMinSize((125,200))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: expenseTypeDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        newTypeSizer = wx.StaticBoxSizer(self.newTypeSizer_staticbox, wx.VERTICAL)
        innerNewTypeSizer = wx.BoxSizer(wx.HORIZONTAL)
        deleteSizer = wx.StaticBoxSizer(self.deleteSizer_staticbox, wx.VERTICAL)
        innerDeleteSizer = wx.BoxSizer(wx.HORIZONTAL)
        editSizer = wx.StaticBoxSizer(self.editSizer_staticbox, wx.VERTICAL)
        sizer_8 = wx.BoxSizer(wx.VERTICAL)
        sizer_8.Add(self.expenseTypeGrid, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_8.Add(self.expenseTypeEditToggle, 0, wx.RIGHT|wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        editSizer.Add(sizer_8, 1, wx.EXPAND, 0)
        sizer_2.Add(editSizer, 1, wx.LEFT|wx.RIGHT|wx.TOP|wx.EXPAND, 5)
        innerDeleteSizer.Add(self.deleteComboBox, 1, wx.RIGHT|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        innerDeleteSizer.Add(self.deleteButton, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        deleteSizer.Add(innerDeleteSizer, 1, wx.EXPAND, 0)
        sizer_2.Add(deleteSizer, 0, wx.LEFT|wx.RIGHT|wx.TOP|wx.EXPAND, 5)
        innerNewTypeSizer.Add(self.newExpenseTypeEntry, 1, wx.RIGHT|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        innerNewTypeSizer.Add(self.addButton, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        newTypeSizer.Add(innerNewTypeSizer, 1, wx.EXPAND, 0)
        sizer_2.Add(newTypeSizer, 0, wx.ALL|wx.EXPAND, 5)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class expenseTypeDialog


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = expenseTypeDialog(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
